# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"^\n\x0eMsgVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\r\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\t\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x05 \x01(\r\"4\n\x0fMsgVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\r\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\"!\n\x05\x45ntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\x05\"\x93\x01\n\x17MsgAppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\r\x12\x10\n\x08leaderId\x18\x02 \x01(\t\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\r\x12\x14\n\x0cleaderCommit\x18\x05 \x01(\r\x12\x17\n\x07\x65ntries\x18\x06 \x03(\x0b\x32\x06.Entry\"9\n\x18MsgAppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\r\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\x86\x01\n\x08RaftNode\x12\x32\n\x0bRequestVote\x12\x0f.MsgVoteRequest\x1a\x10.MsgVoteResponse\"\x00\x12\x46\n\rAppendEntries\x12\x18.MsgAppendEntriesRequest\x1a\x19.MsgAppendEntriesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MSGVOTEREQUEST']._serialized_start=14
  _globals['_MSGVOTEREQUEST']._serialized_end=108
  _globals['_MSGVOTERESPONSE']._serialized_start=110
  _globals['_MSGVOTERESPONSE']._serialized_end=162
  _globals['_ENTRY']._serialized_start=164
  _globals['_ENTRY']._serialized_end=197
  _globals['_MSGAPPENDENTRIESREQUEST']._serialized_start=200
  _globals['_MSGAPPENDENTRIESREQUEST']._serialized_end=347
  _globals['_MSGAPPENDENTRIESRESPONSE']._serialized_start=349
  _globals['_MSGAPPENDENTRIESRESPONSE']._serialized_end=406
  _globals['_RAFTNODE']._serialized_start=409
  _globals['_RAFTNODE']._serialized_end=543
# @@protoc_insertion_point(module_scope)
